namespace RCUnmanaged
{
    runtimeclass Unmanaged
    {
        Unmanaged();
        Int32[] Putcomputer(Boolean hard, Int32 turn);
        Boolean Fullboard();
        Boolean BoardUndo();
        Int32 Checkwin(Boolean change);
        Boolean Puthuman(Int32 row, Int32 col, Int32 turn);
        Int32[] Getchessboard();
        Int32[] Gethistory();
    }
}
